const START_FETCH_FORECAST = 'START_FETCH_FORECAST';
const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS';
const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
const FETCH_FAVORITES_FORECAST_SUCCESS = 'FETCH_FAVORITES_FORECAST_SUCCESS';

export default {
	START_FETCH_FORECAST,
	FETCH_FORECAST_SUCCESS,
	SET_CURRENT_LOCATION,
	FETCH_FAVORITES_FORECAST_SUCCESS
};
